[project]
name = "freeciv_sav"
version = "0.1"
readme = "README.md"
requires-python = ">=3.7"
dependencies = [
    "pyyaml"
]

[project.scripts]
historical_statis = "freeciv_sav.tasks.statis_history:main"
